name: General deploy
run-name: ${{ github.actor }} deploys
on: 
  push:
    branches: 
      - main
jobs:
  Start:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          clean: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.0'

      - name: Install dependencies
        run: npm ci
      - name: Move headers
        run: node move-header.js
      - name: Build application
        run: npm run docs:build
